#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# change for github push
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo -e "\nfrontend myfrontend\
\n\tbind :80,:8080\
\n\tmode http\
\n\tdefault_backend myservers\
\n\nbackend myservers\
\n\tbalance roundrobin\
\n\toption forwardfor\
\n\tserver 4931-web-01 34.201.146.152:80\
\n\tserver 4931-web-02 54.145.50.22:80" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo /etc/init.d/haproxy start